# Coveralls configuration
# https://docs.coveralls.io/configuration

# Service name for GitHub Actions
service_name: github-actions

# Coverage precision
coverage_precision: 2

# Flag configuration for separate test suites
# Flags allow tracking coverage from different test suites separately
# and then merging them into a single report
flag_names:
  daemon:
    description: Daemon + Shared unit test coverage
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  web:
    description: Web unit test coverage
    paths:
      - packages/web/src/
      - packages/shared/src/
  # Offline integration test coverage (matrixized by module)
  daemon-offline-agent:
    description: Daemon offline integration tests - agent module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-session:
    description: Daemon offline integration tests - session module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-rpc:
    description: Daemon offline integration tests - rpc module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-database:
    description: Daemon offline integration tests - database module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-filesystem:
    description: Daemon offline integration tests - filesystem module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-websocket:
    description: Daemon offline integration tests - websocket module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-git:
    description: Daemon offline integration tests - git module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-components:
    description: Daemon offline integration tests - components module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-offline-mcp:
    description: Daemon offline integration tests - mcp module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  # Online integration test coverage (matrixized by module)
  daemon-online-agent:
    description: Daemon online integration tests - agent module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-components:
    description: Daemon online integration tests - components module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-coordinator:
    description: Daemon online integration tests - coordinator module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-convo:
    description: Daemon online integration tests - convo module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-features:
    description: Daemon online integration tests - features module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-lifecycle:
    description: Daemon online integration tests - lifecycle module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-mcp:
    description: Daemon online integration tests - mcp module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-providers:
    description: Daemon online integration tests - providers module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-rewind:
    description: Daemon online integration tests - rewind module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-rpc:
    description: Daemon online integration tests - rpc module
    paths:
      - packages/daemon/src/
      - packages/shared/src/
  daemon-online-sdk:
    description: Daemon online integration tests - sdk module
    paths:
      - packages/daemon/src/
      - packages/shared/src/

# Ignore test files and fixtures
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "**/fixtures/**"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/index.ts"
