/**
 * Type declaration for auto-generated embedded assets module.
 * The actual file (embedded-assets.ts) is generated by scripts/generate-embedded-assets.ts
 * and is gitignored. This declaration provides types for TypeScript checking.
 */

export interface EmbeddedAsset {
	filePath: string;
	mimeType: string;
}

export declare const embeddedAssets: Map<string, EmbeddedAsset>;
